-- Base de datos para Sistema de Solicitudes de Carpetas de Licencias

CREATE DATABASE IF NOT EXISTS carpetas_licencias;
USE carpetas_licencias;

-- Tabla de usuarios (Funcionarios y Administradores)
CREATE TABLE usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    apellido_paterno VARCHAR(100) NOT NULL,
    apellido_materno VARCHAR(100),
    correo VARCHAR(100) NOT NULL UNIQUE,
    contraseña VARCHAR(255) NOT NULL,
    rol ENUM('administrador', 'funcionario') NOT NULL,
    activo TINYINT(1) DEFAULT 1,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabla de municipalidades (Comunas de Chile)
CREATE TABLE municipalidades (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    region VARCHAR(100)
);

-- Tabla de solicitudes
CREATE TABLE solicitudes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre_solicitado VARCHAR(100) NOT NULL,
    apellido_paterno_solicitado VARCHAR(100) NOT NULL,
    apellido_materno_solicitado VARCHAR(100),
    run_solicitado VARCHAR(12) NOT NULL,
    correo_solicitante VARCHAR(100) NOT NULL,
    municipalidad_id INT NOT NULL,
    estado ENUM('Pendiente', 'Cargada', 'Cargada con observaciones', 'No encontrada', 'Rechazada') DEFAULT 'Pendiente',
    observaciones TEXT,
    usuario_id INT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (municipalidad_id) REFERENCES municipalidades(id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- Tabla de bitácora de cambios de estado
CREATE TABLE bitacora_cambios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    solicitud_id INT NOT NULL,
    usuario_id INT,
    estado_anterior ENUM('Pendiente', 'Cargada', 'Cargada con observaciones', 'No encontrada', 'Rechazada'),
    estado_nuevo ENUM('Pendiente', 'Cargada', 'Cargada con observaciones', 'No encontrada', 'Rechazada') NOT NULL,
    observaciones TEXT,
    fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (solicitud_id) REFERENCES solicitudes(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- Tabla de plantillas de correo
CREATE TABLE plantillas_correo (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tipo ENUM('nueva_solicitud', 'estado_cambio', 'solicitud_cargada', 'solicitud_rechazada') NOT NULL UNIQUE,
    asunto VARCHAR(200) NOT NULL,
    cuerpo LONGTEXT NOT NULL,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabla de configuración SMTP
CREATE TABLE config_smtp (
    id INT PRIMARY KEY AUTO_INCREMENT,
    host VARCHAR(100) NOT NULL,
    puerto INT NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    contraseña VARCHAR(255) NOT NULL,
    from_email VARCHAR(100) NOT NULL,
    from_nombre VARCHAR(100) NOT NULL,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabla de configuración general
CREATE TABLE configuracion (
    id INT PRIMARY KEY AUTO_INCREMENT,
    clave VARCHAR(100) NOT NULL UNIQUE,
    valor LONGTEXT NOT NULL,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Insertar municipalidades (Comunas de Chile)
INSERT IGNORE INTO municipalidades (nombre, region) VALUES
('Arica', 'Arica y Parinacota'),
('Camarones', 'Arica y Parinacota'),
('Putre', 'Arica y Parinacota'),
('General Lagos', 'Arica y Parinacota'),
('Iquique', 'Tarapacá'),
('Alto Hospicio', 'Tarapacá'),
('Camiña', 'Tarapacá'),
('Colchane', 'Tarapacá'),
('Huara', 'Tarapacá'),
('Pica', 'Tarapacá'),
('Pozo Almonte', 'Tarapacá'),
('Antofagasta', 'Antofagasta'),
('Mejillones', 'Antofagasta'),
('Sierra Gorda', 'Antofagasta'),
('Taltal', 'Antofagasta'),
('Calama', 'Antofagasta'),
('Conchi', 'Antofagasta'),
('San Pedro de Atacama', 'Antofagasta'),
('Tocopilla', 'Antofagasta'),
('María Elena', 'Antofagasta'),
('Ovalle', 'Coquimbo'),
('Andacollo', 'Coquimbo'),
('Canela', 'Coquimbo'),
('Combarbalá', 'Coquimbo'),
('Hurtado', 'Coquimbo'),
('La Higuera', 'Coquimbo'),
('La Serena', 'Coquimbo'),
('Coquimbo', 'Coquimbo'),
('Peñasco', 'Coquimbo'),
('Tongoy', 'Coquimbo'),
('Vallenar', 'Atacama'),
('Caldera', 'Atacama'),
('Copiapó', 'Atacama'),
('Tierra Amarilla', 'Atacama'),
('Chañaral', 'Atacama'),
('Diego de Almagro', 'Atacama'),
('Valparaíso', 'Valparaíso'),
('Casablanca', 'Valparaíso'),
('Concón', 'Valparaíso'),
('Juan Fernández', 'Valparaíso'),
('Puchuncaví', 'Valparaíso'),
('Quintero', 'Valparaíso'),
('Viña del Mar', 'Valparaíso'),
('Isla de Pascua', 'Valparaíso'),
('Villa Alemana', 'Valparaíso'),
('Quilpué', 'Valparaíso'),
('La Calera', 'Valparaíso'),
('Quillota', 'Valparaíso'),
('La Cruz', 'Valparaíso'),
('Limache', 'Valparaíso'),
('Nogales', 'Valparaíso'),
('Cabildo', 'Valparaíso'),
('Caleta de Campos', 'Valparaíso'),
('La Ligua', 'Valparaíso'),
('Papudo', 'Valparaíso'),
('Petorca', 'Valparaíso'),
('Zapallar', 'Valparaíso'),
('Los Andes', 'Valparaíso'),
('Calle Larga', 'Valparaíso'),
('Rinconada', 'Valparaíso'),
('San Feliciano', 'Valparaíso'),
('Aconcagua', 'Valparaíso'),
('San Esteban', 'Valparaíso'),
('Santa María', 'Valparaíso'),
('Limache', 'Valparaíso'),
('Santiago', 'Metropolitana'),
('Lampa', 'Metropolitana'),
('Conchali', 'Metropolitana'),
('Pudahuel', 'Metropolitana'),
('Blanco Encalada', 'Metropolitana'),
('Colina', 'Metropolitana'),
('San Bernardo', 'Metropolitana'),
('Pirque', 'Metropolitana'),
('San José de Maipo', 'Metropolitana'),
('Puente Alto', 'Metropolitana'),
('La Florida', 'Metropolitana'),
('La Pintana', 'Metropolitana'),
('La Granja', 'Metropolitana'),
('El Bosque', 'Metropolitana'),
('Ñuñoa', 'Metropolitana'),
('Las Condes', 'Metropolitana'),
('Lo Barnechea', 'Metropolitana'),
('Vitacura', 'Metropolitana'),
('San Ramón', 'Metropolitana'),
('Providencia', 'Metropolitana'),
('Lo Espejo', 'Metropolitana'),
('Maipú', 'Metropolitana'),
('Peñalolén', 'Metropolitana'),
('Macul', 'Metropolitana'),
('Quinta Normal', 'Metropolitana'),
('Curicó', 'Maule'),
('Hualañé', 'Maule'),
('Licantén', 'Maule'),
('Molina', 'Maule'),
('Rauco', 'Maule'),
('Romeral', 'Maule'),
('Sagrada Familia', 'Maule'),
('Teno', 'Maule'),
('Vichuquén', 'Maule'),
('Talca', 'Maule'),
('Constitución', 'Maule'),
('Curepto', 'Maule'),
('Empedrado', 'Maule'),
('Maule', 'Maule'),
('Pencahue', 'Maule'),
('Pelarco', 'Maule'),
('Río Claro', 'Maule'),
('San Clemente', 'Maule'),
('San Javier', 'Maule'),
('Villa Alegre', 'Maule'),
('Linares', 'Maule'),
('Chillan', 'Ñuble'),
('Bulnes', 'Ñuble'),
('Chillán Viejo', 'Ñuble'),
('El Carmen', 'Ñuble'),
('Pemuco', 'Ñuble'),
('Pinto', 'Ñuble'),
('Quillón', 'Ñuble'),
('Quirihue', 'Ñuble'),
('Ránquil', 'Ñuble'),
('San Ignacio', 'Ñuble'),
('Yungay', 'Ñuble'),
('San Carlos', 'Ñuble'),
('Cabrero', 'Ñuble'),
('Laja', 'Ñuble'),
('Los Ángeles', 'Ñuble'),
('Mulchén', 'Ñuble'),
('Nacimiento', 'Ñuble'),
('Negrete', 'Ñuble'),
('Santa Bárbara', 'Ñuble'),
('Tucapel', 'Ñuble'),
('Concepción', 'Biobío'),
('Chiguayante', 'Biobío'),
('Hualpencillo', 'Biobío'),
('Hualqui', 'Biobío'),
('Lota', 'Biobío'),
('Penco', 'Biobío'),
('San Pedro de la Paz', 'Biobío'),
('Santa Juana', 'Biobío'),
('Talcahuano', 'Biobío'),
('Tome', 'Biobío'),
('Lebu', 'Biobío'),
('Arauco', 'Biobío'),
('Cañete', 'Biobío'),
('Curanilahue', 'Biobío'),
('Los Álamos', 'Biobío'),
('Tirúa', 'Biobío'),
('Los Ángeles', 'Biobío'),
('Angol', 'Araucanía'),
('Collipulli', 'Araucanía'),
('Curacautín', 'Araucanía'),
('Ercilla', 'Araucanía'),
('Lonquimay', 'Araucanía'),
('Los Sauces', 'Araucanía'),
('Lumaco', 'Araucanía'),
('Purén', 'Araucanía'),
('Renaico', 'Araucanía'),
('Temuco', 'Araucanía'),
('Carahue', 'Araucanía'),
('Cunco', 'Araucanía'),
('Curarrehue', 'Araucanía'),
('Freire', 'Araucanía'),
('Galvarino', 'Araucanía'),
('Gorbea', 'Araucanía'),
('Lautaro', 'Araucanía'),
('Loncoche', 'Araucanía'),
('Nueva Imperial', 'Araucanía'),
('Padre Las Casas', 'Araucanía'),
('Perkinenco', 'Araucanía'),
('Pucón', 'Araucanía'),
('Puerto Saavedra', 'Araucanía'),
('Saavedra', 'Araucanía'),
('Teodoro Schmidt', 'Araucanía'),
('Tolten', 'Araucanía'),
('Valdivia', 'Los Ríos'),
('Corral', 'Los Ríos'),
('Lachón', 'Los Ríos'),
('Mariquina', 'Los Ríos'),
('Máfil', 'Los Ríos'),
('Paillaco', 'Los Ríos'),
('Panguipulli', 'Los Ríos'),
('La Unión', 'Los Ríos'),
('Futrono', 'Los Ríos'),
('Lago Ranco', 'Los Ríos'),
('Puerto Varas', 'Los Lagos'),
('Carelmapu', 'Los Lagos'),
('Cochamó', 'Los Lagos'),
('Dalcahue', 'Los Lagos'),
('Fresia', 'Los Lagos'),
('Frutillar', 'Los Lagos'),
('Llanquihue', 'Los Lagos'),
('Maullín', 'Los Lagos'),
('Osorno', 'Los Lagos'),
('Puerto Montt', 'Los Lagos'),
('Purranque', 'Los Lagos'),
('Puyehue', 'Los Lagos'),
('Quellón', 'Los Lagos'),
('Quemchi', 'Los Lagos'),
('Quinchao', 'Los Lagos'),
('Río Negro', 'Los Lagos'),
('San Juan de la Costa', 'Los Lagos'),
('San Pablo', 'Los Lagos'),
('Chaitén', 'Los Lagos'),
('Futaleufú', 'Los Lagos'),
('Palena', 'Los Lagos'),
('Coyhaique', 'Aysén'),
('Lago Verde', 'Aysén'),
('Mallín Grande', 'Aysén'),
('Balmaceda', 'Aysén'),
('Cerro Castillo', 'Aysén'),
('Cisnes', 'Aysén'),
('Guaitecas', 'Aysén'),
('Puyuhuapi', 'Aysén'),
('Aysén', 'Aysén'),
('Chile Chico', 'Aysén'),
('Río Ibáñez', 'Aysén'),
('Magallanes', 'Magallanes'),
('Punta Arenas', 'Magallanes'),
('Puerto Natales', 'Magallanes'),
('Laguna Blanca', 'Magallanes'),
('Río Verde', 'Magallanes'),
('San Gregorio', 'Magallanes'),
('Porvenir', 'Magallanes'),
('Primavera', 'Magallanes'),
('Timaukel', 'Magallanes');

-- Insertar plantillas de correo por defecto
INSERT IGNORE INTO plantillas_correo (tipo, asunto, cuerpo) VALUES
('nueva_solicitud', 'Nueva solicitud de carpeta de licencia #{solicitud_id}', '<h2>Nueva solicitud de carpeta de licencia</h2><p>Estimado/a funcionario/a:</p><p>Se informa que ha ingresado una nueva solicitud de carpeta de licencia al sistema.</p><p><strong>N.º de solicitud:</strong> {solicitud_id}<br><strong>Persona solicitada:</strong> {nombre} {apellido_paterno} {apellido_materno}<br><strong>RUN:</strong> {run}<br><strong>Municipalidad solicitante:</strong> {municipalidad}<br><strong>Correo del solicitante:</strong> {correo_solicitante}</p><p>Por favor, ingrese al sistema para revisar y gestionar esta solicitud.</p><p>Atentamente,<br>Sistema de Carpetas de Licencias<br>Municipalidad de Los Lagos</p>'),
('estado_cambio', 'Estado de su solicitud actualizado', 'El estado de su solicitud ha sido actualizado a: {estado}\n\nDetalles de la solicitud:\nNombre: {nombre} {apellido_paterno} {apellido_materno}\nRUN: {run}\n\nObservaciones: {observaciones}'),
('solicitud_cargada', 'Solicitud completada', 'La carpeta de licencia ha sido cargada exitosamente.\n\nDetalles:\nNombre: {nombre}\nRUN: {run}'),
('solicitud_rechazada', 'Solicitud rechazada', 'Lamentamos informar que su solicitud ha sido rechazada.\n\nMotivo: {observaciones}');

-- Crear usuario administrador por defecto (contraseña: admin123)
INSERT IGNORE INTO usuarios (nombre, apellido_paterno, apellido_materno, correo, contraseña, rol) VALUES
('Administrador', 'Sistema', '', 'admin@carpetaslicencias.cl', '$2y$10$VgZjArArVUpAowarA6QhAuJiGBZaLJEigz6ivwlwwq7riaDOBBbRu', 'administrador');
